[package]
name = "x3dh-xor"
version = "0.1.1"
edition = "2021"
authors = ["XOR·APPS Developers <developers@xorapps.cloud>"]
license = "Apache-2.0"
description = "Extended Triple Diffie-Hellman Key Agreement Library"
readme = "README.md"
keywords = ["x3dh", "diffe-hellman", "key exchange", "signal"]
categories = ["authentication", "cryptography"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayvec = "0.7.2"
blake3 = "1.3.3"
ed25519-dalek = { version = "1.0.1", default-features = false, features = [
    "u64_backend",
] }
rand_core = { version = "0.6.4", features = ["getrandom"] }
tai64 = "4.0.0"
x25519-dalek = "2.0.0-pre.1"

[dev-dependencies]
rand = "0.7"
ed25519-dalek = { version = "1.0.1", default-features = false, features = [
    "u64_backend",
    "rand",
] }
